### ISSUE TITLE
the program cannot find the path of the model

### ISSUE THREAD

**Issue by lollo1252** [zjkhurry/stereopsis-anything#1]
it give me a error that there was nothing or the path is non existent, i tried diffent path to like /user/lollo/stereopis-anithing/model/dephanything... and this work if i use cd in terminal but the program return me this error "Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/lollo/.pyenv/versions/3.8.20/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "run.py", line 305, in run
    model = ct.models.MLModel(model_path, compute_units=u)
  File "/Users/lollo/.pyenv/versions/3.8.20/lib/python3.8/site-packages/coremltools/models/model.py", line 403, in __init__
    self.__proxy__, self._spec, self._framework_error = self._get_proxy_and_spec(
  File "/Users/lollo/.pyenv/versions/3.8.20/lib/python3.8/site-packages/coremltools/models/model.py", line 465, in _get_proxy_and_spec
    specification = _load_spec(filename)
  File "/Users/lollo/.pyenv/versions/3.8.20/lib/python3.8/site-packages/coremltools/models/utils.py", line 255, in load_spec
    with open(specfile, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/model/model/depth_anything_v2_vits2.mlpackage'
"

**Comment by zjkhurry** [comment]
you didn't need specify a model path, just run command in "stereopis-anithing" folder.
```bash
python3 run.py
```
 In case you want to use your own model, you can download the new code and use the new model with
```bash
python3 run.py -m  "/user/lollo/stereopis-anithing/model/depth_anything_v2_vits2.mlpackage"
```

**Comment by lollo1252** [comment]
> you didn't need specify a model path, just run command in "stereopis-anithing" folder.
> ```bash
> python3 run.py
> ```
>  In case you want to use your own model, you can download the new code and use the new model with
> ```bash
> python3 run.py -m  "/user/lollo/stereopis-anithing/model/depth_anything_v2_vits2.mlpackage"
> ```
> 

I tried run the the program from the folder, maybe is because i am using venv? Or because i used a tool to downgrade python to 3.8 because using the latest version of python with pip tell me that all version of torch and torchvision are not compatible?

**Comment by zjkhurry** [comment]
@lollo1252 It look like it only couldn't find the AI model. Could you try the latest run.py with or without "-m".
